const Lingua = {
    translations: {
        en: {
            php: {
                messages: {
                    app_name: 'Campmaster',
                    app_description: 'A web application for managing your campsite reservations and activities.',
                    sidebar: {
                        main: 'General',
                        configuration: 'Configuration',
                        dashboard: 'Dashboard',
                        reservations: 'Reservations',
                        activities: 'Activities',
                        guests: 'Guests',
                        settings: 'Settings',
                        logout: 'Logout',
                        sites: 'Sites',
                        site_categories: 'Site Categories',
                    },
                    datatable: { columns: 'Columns', no_results: 'No results.', search_placeholder: 'Search...' },
                    common: { buttons: { edit: 'Edit', update: 'Update', create: 'Create', cancel: 'Cancel' } },
                    pagination: { page: 'Page', of: 'of', total: 'total', previous: 'Previous', next: 'Next' },
                    guests: {
                        breadcrumb: 'Guests',
                        title: 'Guests',
                        subtitle: 'Browse and manage your guests',
                        search_placeholder: 'Search guests...',
                        columns: { name: 'Name', email: 'Email', city: 'City', added: 'Added' },
                        actions: { create: 'Create guest' },
                        edit: {
                            title: 'Edit Guest ":name"',
                            subtitle: 'Edit guest details',
                            form_title: 'General Information',
                            success_message: { title: 'Guest updated successfully', description: 'The guest has been successfully updated.' },
                            errors: 'Failed to update guest.',
                            buttons: { update: 'Update', save: 'Save', cancel: 'Cancel' },
                            fields: {
                                firstname: 'First Name',
                                lastname: 'Last Name',
                                email: 'Email',
                                street: 'Street',
                                house_number: 'House Number',
                                postal_code: 'Postal Code',
                                city: 'City',
                                country: 'Country',
                            },
                        },
                        create: {
                            title: 'Create Guest',
                            subtitle: 'Create a new guest',
                            success_message: { title: 'Guest created successfully', description: 'The guest has been successfully created.' },
                            errors: 'Failed to create guest.',
                            buttons: { create: 'Create', cancel: 'Cancel' },
                            fields: {
                                firstname: 'First Name',
                                lastname: 'Last Name',
                                email: 'Email',
                                street: 'Street',
                                house_number: 'House Number',
                                postal_code: 'Postal Code',
                                city: 'City',
                                country: 'Country',
                            },
                        },
                    },
                    bookings: { breadcrumb: 'Bookings', title: 'Bookings', subtitle: 'Manage your bookings and reservations' },
                    sites: {
                        breadcrumb: 'Sites',
                        title: 'Sites',
                        subtitle: 'Manage your campsite sites and other rentable properties',
                        actions: { create: 'Create site' },
                        columns: { name: 'Name', category: 'Category', added: 'Added', description: 'Description' },
                        fields: { name: 'Name', description: 'Description', category: 'Category' },
                        placeholders: { select_category: 'Select a category' },
                        create: {
                            title: 'Create Site',
                            subtitle: 'Create a new site',
                            success_message: { title: 'Site created successfully', description: 'The site has been successfully created.' },
                            buttons: { create: 'Create', cancel: 'Cancel' },
                        },
                        edit: {
                            title: 'Edit Site ":name"',
                            subtitle: 'Edit site details',
                            form_title: 'General Information',
                            success_message: { title: 'Site updated successfully', description: 'The site has been successfully updated.' },
                            buttons: { update: 'Update', cancel: 'Cancel' },
                        },
                    },
                    site_categories: {
                        breadcrumb: 'Site Categories',
                        title: 'Site Categories',
                        subtitle: 'Manage your site categories',
                        actions: { create: 'Create category' },
                        columns: { name: 'Name', slug: 'Slug', sites: 'Sites', added: 'Added', description: 'Description' },
                        fields: { name: 'Name', description: 'Description' },
                        create: {
                            title: 'Create Category',
                            subtitle: 'Create a new site category',
                            success_message: { title: 'Category created successfully', description: 'The category has been successfully created.' },
                            buttons: { create: 'Create', cancel: 'Cancel' },
                        },
                        edit: {
                            title: 'Edit Category ":name"',
                            subtitle: 'Edit category details',
                            form_title: 'General Information',
                            success_message: { title: 'Category updated successfully', description: 'The category has been successfully updated.' },
                            buttons: { update: 'Update', cancel: 'Cancel' },
                        },
                    },
                    settings: {
                        title: 'Settings',
                        description: 'Manage your profile and account settings',
                        appearance: {
                            title: 'Appearance settings',
                            description: "Update your account's appearance settings",
                            language: {
                                title: 'Language',
                                description: 'Choose the language used across the application',
                                select_label: 'Select language',
                                en: 'English',
                                nl: 'Dutch',
                            },
                        },
                    },
                },
            },
            json: [],
        },
        nl: {
            php: {
                messages: {
                    app_name: 'Campmaster',
                    app_description: 'Een webapplicatie voor het beheren van je campingreserveringen en activiteiten.',
                    sidebar: {
                        main: 'Algemeen',
                        configuration: 'Configuratie',
                        dashboard: 'Dashboard',
                        reservations: 'Reserveringen',
                        activities: 'Activiteiten',
                        guests: 'Gasten',
                        settings: 'Instellingen',
                        logout: 'Uitloggen',
                        sites: 'Plaatsen',
                        site_categories: 'Plaatstypen',
                    },
                    datatable: { columns: 'Kolommen', no_results: 'Geen resultaten.', search_placeholder: 'Zoeken...' },
                    common: { buttons: { edit: 'Bewerken', update: 'Bijwerken', create: 'Aanmaken', cancel: 'Annuleren' } },
                    pagination: { page: 'Pagina', of: 'van', total: 'totaal', previous: 'Vorige', next: 'Volgende' },
                    guests: {
                        breadcrumb: 'Gasten',
                        title: 'Gasten',
                        subtitle: 'Blader en beheer je gasten',
                        search_placeholder: 'Zoek gasten...',
                        columns: { name: 'Naam', email: 'E-mailadres', city: 'Plaats', added: 'Toegevoegd' },
                        actions: { create: 'Gast aanmaken' },
                        edit: {
                            title: 'Gast ":name" bewerken',
                            subtitle: 'Gastgegevens bewerken',
                            form_title: 'Algemene informatie',
                            success_message: { title: 'Gast succesvol bijgewerkt', description: 'De gast is succesvol bijgewerkt.' },
                            errors: 'Bijwerken van gast mislukt.',
                            buttons: { update: 'Bijwerken', save: 'Opslaan', cancel: 'Annuleren' },
                            fields: {
                                firstname: 'Voornaam',
                                lastname: 'Achternaam',
                                email: 'E-mailadres',
                                street: 'Straat',
                                house_number: 'Huisnummer',
                                postal_code: 'Postcode',
                                city: 'Plaats',
                                country: 'Land',
                            },
                        },
                        create: {
                            title: 'Gast aanmaken',
                            subtitle: 'Maak een nieuwe gast aan',
                            success_message: { title: 'Gast succesvol aangemaakt', description: 'De gast is succesvol aangemaakt.' },
                            errors: 'Aanmaken van gast mislukt.',
                            buttons: { create: 'Aanmaken', cancel: 'Annuleren' },
                            fields: {
                                firstname: 'Voornaam',
                                lastname: 'Achternaam',
                                email: 'E-mailadres',
                                street: 'Straat',
                                house_number: 'Huisnummer',
                                postal_code: 'Postcode',
                                city: 'Plaats',
                                country: 'Land',
                            },
                        },
                    },
                    bookings: { breadcrumb: 'Boekingen', title: 'Boekingen', subtitle: 'Beheer je boekingen en reserveringen' },
                    sites: {
                        breadcrumb: 'Plaatsen',
                        title: 'Plaatsen',
                        subtitle: 'Beheer je kampeerplaatsen en andere verhuureenheden',
                        actions: { create: 'Plaats aanmaken' },
                        columns: { name: 'Naam', category: 'Categorie', added: 'Toegevoegd', description: 'Beschrijving' },
                        fields: { name: 'Naam', description: 'Beschrijving', category: 'Categorie' },
                        placeholders: { select_category: 'Selecteer een categorie' },
                        create: {
                            title: 'Plaats aanmaken',
                            subtitle: 'Maak een nieuwe plaats aan',
                            success_message: { title: 'Plaats succesvol aangemaakt', description: 'De plaats is succesvol aangemaakt.' },
                            buttons: { create: 'Aanmaken', cancel: 'Annuleren' },
                        },
                        edit: {
                            title: 'Plaats ":name" bewerken',
                            subtitle: 'Plaatsgegevens bewerken',
                            form_title: 'Algemene informatie',
                            success_message: { title: 'Plaats succesvol bijgewerkt', description: 'De plaats is succesvol bijgewerkt.' },
                            buttons: { update: 'Bijwerken', cancel: 'Annuleren' },
                        },
                    },
                    site_categories: {
                        breadcrumb: 'Plaatstypen',
                        title: 'Plaatstypen',
                        subtitle: 'Beheer je plaatscategorie\u00ebn',
                        actions: { create: 'Categorie aanmaken' },
                        columns: { name: 'Naam', slug: 'Slug', sites: 'Plaatsen', added: 'Toegevoegd', description: 'Beschrijving' },
                        fields: { name: 'Naam', description: 'Beschrijving' },
                        create: {
                            title: 'Categorie aanmaken',
                            subtitle: 'Maak een nieuwe plaatscategorie aan',
                            success_message: { title: 'Categorie succesvol aangemaakt', description: 'De categorie is succesvol aangemaakt.' },
                            buttons: { create: 'Aanmaken', cancel: 'Annuleren' },
                        },
                        edit: {
                            title: 'Categorie ":name" bewerken',
                            subtitle: 'Categoriegegevens bewerken',
                            form_title: 'Algemene informatie',
                            success_message: { title: 'Categorie succesvol bijgewerkt', description: 'De categorie is succesvol bijgewerkt.' },
                            buttons: { update: 'Bijwerken', cancel: 'Annuleren' },
                        },
                    },
                    settings: {
                        title: 'Instellingen',
                        description: 'Beheer je profiel- en accountinstellingen',
                        appearance: {
                            title: 'Weergave-instellingen',
                            description: 'Werk de weergave-instellingen van je account bij',
                            language: {
                                title: 'Taal',
                                description: 'Kies de taal die in de applicatie wordt gebruikt',
                                select_label: 'Selecteer taal',
                                en: 'Engels',
                                nl: 'Nederlands',
                            },
                        },
                    },
                },
            },
            json: [],
        },
    },
};

export { Lingua };
